/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

/*
 Original Source(NanoVG):
 Copyright (c) 2013 Mikko Mononen memon@inside.org
*/

module bindbc.nanovg.loader;

public
{
    import bindbc.nanovg.types;
    import bindbc.nanovg.funcs;    
}

version(BindNanovg_Static) {}
else version = BindNanovg_Dynamic;

version(BindNanovg_Dynamic):

import bindbc.loader;

private {
    SharedLib lib;
    NanovgSupport loadedVersion;
}

enum NanovgSupport {
    noLibrary,
    badLibrary,
    Nanovg
}

@nogc nothrow:

void unloadNanovg()
{
    if(lib != invalidHandle) {
        lib.unload();
    }
}

NanovgSupport loadedNanovgVersion() { return loadedVersion; }

bool isNanovgLoaded() { return lib != invalidHandle; }

NanovgSupport loadNanovg()
{
    version(Windows) {
        const(char)[][1] libNames = ["nanovg.dll"];
    }
    else version(OSX) {
        const(char)[][3] libNames = [
            "../Frameworks/nanovg.framework/nanovg",
            "/Library/Frameworks/nanovg.framework/nanovg",
            "/System/Library/Frameworks/nanovg.framework/nanovg"
        ];
    }
    else version(Posix) {
        const(char)[][1] libNames = [
            "libnanovg.so"
        ];
    }
    else static assert(0, "bindbc-nanovg is not yet supported on this platform");
    
    NanovgSupport ret;
    foreach(name; libNames) {
        ret = loadNanovg(name.ptr);
        if(ret != NanovgSupport.noLibrary) break;
    }
    return ret;
}

NanovgSupport loadNanovg(const(char)* libName)
{
    if(lib == invalidHandle) {
        lib = load(libName);
        if(lib == invalidHandle) {
            return NanovgSupport.noLibrary;
        }
    }

    auto errCount = errorCount();

    version(NanovgGL2)
    {
        lib.bindSymbol(cast(void**)&nvgCreateGL2, "nvgCreateGL2");
        lib.bindSymbol(cast(void**)&nvgDeleteGL2, "nvgDeleteGL2");
        lib.bindSymbol(cast(void**)&nvglImageHandleGL2, "nvglImageHandleGL2");
    }
    else version(NanovgGL3)
    {
        lib.bindSymbol(cast(void**)&nvgCreateGL3, "nvgCreateGL3");
        lib.bindSymbol(cast(void**)&nvgDeleteGL3, "nvgDeleteGL3");
        lib.bindSymbol(cast(void**)&nvglCreateImageFromHandleGL3, "nvglCreateImageFromHandleGL3");
        lib.bindSymbol(cast(void**)&nvglImageHandleGL3, "nvglImageHandleGL3");
    }
    else version(NanovgGLES2)
    {
        lib.bindSymbol(cast(void**)&nvgCreateGLES2, "nvgCreateGLES2");
        lib.bindSymbol(cast(void**)&nvgDeleteGLES2, "nvgDeleteGLES2");
        lib.bindSymbol(cast(void**)&nvglCreateImageFromHandleGLES2, "nvglCreateImageFromHandleGLES2");
    }
    
    lib.bindSymbol(cast(void**)&nvgBeginFrame, "nvgBeginFrame");
    lib.bindSymbol(cast(void**)&nvgCancelFrame, "nvgCancelFrame");
    lib.bindSymbol(cast(void**)&nvgEndFrame, "nvgEndFrame");
    lib.bindSymbol(cast(void**)&nvgGlobalCompositeOperation, "nvgGlobalCompositeOperation");
    lib.bindSymbol(cast(void**)&nvgGlobalCompositeBlendFunc, "nvgGlobalCompositeBlendFunc");
    lib.bindSymbol(cast(void**)&nvgGlobalCompositeBlendFuncSeparate, "nvgGlobalCompositeBlendFuncSeparate");
    lib.bindSymbol(cast(void**)&nvgRGB, "nvgRGB");
    lib.bindSymbol(cast(void**)&nvgRGBf, "nvgRGBf");
    lib.bindSymbol(cast(void**)&nvgRGBA, "nvgRGBA");
    lib.bindSymbol(cast(void**)&nvgRGBAf, "nvgRGBAf");
    lib.bindSymbol(cast(void**)&nvgLerpRGBA, "nvgLerpRGBA");
    lib.bindSymbol(cast(void**)&nvgTransRGBA, "nvgTransRGBA");
    lib.bindSymbol(cast(void**)&nvgTransRGBAf, "nvgTransRGBAf");
    lib.bindSymbol(cast(void**)&nvgHSL, "nvgHSL");
    lib.bindSymbol(cast(void**)&nvgHSLA, "nvgHSLA");
    lib.bindSymbol(cast(void**)&nvgSave, "nvgSave");
    lib.bindSymbol(cast(void**)&nvgRestore, "nvgRestore");
    lib.bindSymbol(cast(void**)&nvgReset, "nvgReset");
    lib.bindSymbol(cast(void**)&nvgStrokeColor, "nvgStrokeColor");
    lib.bindSymbol(cast(void**)&nvgStrokePaint, "nvgStrokePaint");
    lib.bindSymbol(cast(void**)&nvgFillColor, "nvgFillColor");
    lib.bindSymbol(cast(void**)&nvgFillPaint, "nvgFillPaint");
    lib.bindSymbol(cast(void**)&nvgMiterLimit, "nvgMiterLimit");
    lib.bindSymbol(cast(void**)&nvgStrokeWidth, "nvgStrokeWidth");
    lib.bindSymbol(cast(void**)&nvgLineCap, "nvgLineCap");
    lib.bindSymbol(cast(void**)&nvgLineJoin, "nvgLineJoin");
    lib.bindSymbol(cast(void**)&nvgGlobalAlpha, "nvgGlobalAlpha");
    lib.bindSymbol(cast(void**)&nvgResetTransform, "nvgResetTransform");
    lib.bindSymbol(cast(void**)&nvgTransform, "nvgTransform");
    lib.bindSymbol(cast(void**)&nvgTranslate, "nvgTranslate");
    lib.bindSymbol(cast(void**)&nvgRotate, "nvgRotate");
    lib.bindSymbol(cast(void**)&nvgSkewX, "nvgSkewX");
    lib.bindSymbol(cast(void**)&nvgSkewY, "nvgSkewY");
    lib.bindSymbol(cast(void**)&nvgScale, "nvgScale");
    lib.bindSymbol(cast(void**)&nvgCurrentTransform, "nvgCurrentTransform");
    lib.bindSymbol(cast(void**)&nvgTransformIdentity, "nvgTransformIdentity");
    lib.bindSymbol(cast(void**)&nvgTransformTranslate, "nvgTransformTranslate");
    lib.bindSymbol(cast(void**)&nvgTransformScale, "nvgTransformScale");
    lib.bindSymbol(cast(void**)&nvgTransformRotate, "nvgTransformRotate");
    lib.bindSymbol(cast(void**)&nvgTransformSkewX, "nvgTransformSkewX");
    lib.bindSymbol(cast(void**)&nvgTransformSkewY, "nvgTransformSkewY");
    lib.bindSymbol(cast(void**)&nvgTransformMultiply, "nvgTransformMultiply");
    lib.bindSymbol(cast(void**)&nvgTransformPremultiply, "nvgTransformPremultiply");
    lib.bindSymbol(cast(void**)&nvgTransformInverse, "nvgTransformInverse");
    lib.bindSymbol(cast(void**)&nvgTransformPoint, "nvgTransformPoint");
    lib.bindSymbol(cast(void**)&nvgDegToRad, "nvgDegToRad");
    lib.bindSymbol(cast(void**)&nvgRadToDeg, "nvgRadToDeg");
    lib.bindSymbol(cast(void**)&nvgCreateImage, "nvgCreateImage");
    lib.bindSymbol(cast(void**)&nvgCreateImageMem, "nvgCreateImageMem");
    lib.bindSymbol(cast(void**)&nvgCreateImageRGBA, "nvgCreateImageRGBA");
    lib.bindSymbol(cast(void**)&nvgUpdateImage, "nvgUpdateImage");
    lib.bindSymbol(cast(void**)&nvgImageSize, "nvgImageSize");
    lib.bindSymbol(cast(void**)&nvgDeleteImage, "nvgDeleteImage");
    lib.bindSymbol(cast(void**)&nvgLinearGradient, "nvgLinearGradient");
    lib.bindSymbol(cast(void**)&nvgBoxGradient, "nvgBoxGradient");
    lib.bindSymbol(cast(void**)&nvgRadialGradient, "nvgRadialGradient");
    lib.bindSymbol(cast(void**)&nvgImagePattern, "nvgImagePattern");
    lib.bindSymbol(cast(void**)&nvgScissor, "nvgScissor");
    lib.bindSymbol(cast(void**)&nvgIntersectScissor, "nvgIntersectScissor");
    lib.bindSymbol(cast(void**)&nvgResetScissor, "nvgResetScissor");
    lib.bindSymbol(cast(void**)&nvgBeginPath, "nvgBeginPath");
    lib.bindSymbol(cast(void**)&nvgMoveTo, "nvgMoveTo");
    lib.bindSymbol(cast(void**)&nvgLineTo, "nvgLineTo");
    lib.bindSymbol(cast(void**)&nvgBezierTo, "nvgBezierTo");
    lib.bindSymbol(cast(void**)&nvgQuadTo, "nvgQuadTo");
    lib.bindSymbol(cast(void**)&nvgArcTo, "nvgArcTo");
    lib.bindSymbol(cast(void**)&nvgClosePath, "nvgClosePath");
    lib.bindSymbol(cast(void**)&nvgPathWinding, "nvgPathWinding");
    lib.bindSymbol(cast(void**)&nvgArc, "nvgArc");
    lib.bindSymbol(cast(void**)&nvgRect, "nvgRect");
    lib.bindSymbol(cast(void**)&nvgRoundedRect, "nvgRoundedRect");
    lib.bindSymbol(cast(void**)&nvgRoundedRectVarying, "nvgRoundedRectVarying");
    lib.bindSymbol(cast(void**)&nvgEllipse, "nvgEllipse");
    lib.bindSymbol(cast(void**)&nvgCircle, "nvgCircle");
    lib.bindSymbol(cast(void**)&nvgFill, "nvgFill");
    lib.bindSymbol(cast(void**)&nvgStroke, "nvgStroke");
    lib.bindSymbol(cast(void**)&nvgCreateFont, "nvgCreateFont");
    lib.bindSymbol(cast(void**)&nvgCreateFontMem, "nvgCreateFontMem");
    lib.bindSymbol(cast(void**)&nvgFindFont, "nvgFindFont");
    lib.bindSymbol(cast(void**)&nvgAddFallbackFontId, "nvgAddFallbackFontId");
    lib.bindSymbol(cast(void**)&nvgAddFallbackFont, "nvgAddFallbackFont");
    lib.bindSymbol(cast(void**)&nvgFontSize, "nvgFontSize");
    lib.bindSymbol(cast(void**)&nvgFontBlur, "nvgFontBlur");
    lib.bindSymbol(cast(void**)&nvgTextLetterSpacing, "nvgTextLetterSpacing");
    lib.bindSymbol(cast(void**)&nvgTextLineHeight, "nvgTextLineHeight");
    lib.bindSymbol(cast(void**)&nvgTextAlign, "nvgTextAlign");
    lib.bindSymbol(cast(void**)&nvgFontFaceId, "nvgFontFaceId");
    lib.bindSymbol(cast(void**)&nvgFontFace, "nvgFontFace");
    lib.bindSymbol(cast(void**)&nvgText, "nvgText");
    lib.bindSymbol(cast(void**)&nvgTextBox, "nvgTextBox");
    lib.bindSymbol(cast(void**)&nvgTextBounds, "nvgTextBounds");
    lib.bindSymbol(cast(void**)&nvgTextBoxBounds, "nvgTextBoxBounds");
    lib.bindSymbol(cast(void**)&nvgTextGlyphPositions, "nvgTextGlyphPositions");
    lib.bindSymbol(cast(void**)&nvgTextMetrics, "nvgTextMetrics");
    lib.bindSymbol(cast(void**)&nvgTextBreakLines, "nvgTextBreakLines");
    lib.bindSymbol(cast(void**)&nvgCreateInternal, "nvgCreateInternal");
    lib.bindSymbol(cast(void**)&nvgDeleteInternal, "nvgDeleteInternal");
    lib.bindSymbol(cast(void**)&nvgInternalParams, "nvgInternalParams");
    lib.bindSymbol(cast(void**)&nvgDebugDumpPathCache, "nvgDebugDumpPathCache");
    
    if(errorCount() != errCount) loadedVersion = NanovgSupport.badLibrary;
    else loadedVersion = NanovgSupport.Nanovg;

    return loadedVersion;
}